[build]
  command = "make build"
  publish = "content/.vuepress/dist/"

[[redirects]]
from = "/docs/getting-started/"
to = "/docs/"

[[redirects]]
from = "/community/events.html"
to = "/community/#events"

[[redirects]]
from = "/docs/concepts.html"
to = "/docs/what-is-kudo.html#under-the-hood"

[[redirects]]
from = "/blog/blog-2020-07-building-your-first-operator-2.html"
to = "/blog/blog-2020-07-13-building-your-first-operator-2.html"

[[redirects]]
from = "/docs/cli.html#setup-the-kudo-kubectl-plugin"
to = "/docs/cli/installation.html"

[[redirects]]
from = "/docs/cli.html#commands"
to = "/docs/cli/commands.html"

[[redirects]]
from = "/docs/cli.html#flags"
to = "/docs/cli/commands.html"

[[redirects]]
from = "/docs/cli.html#examples"
to = "/docs/cli/examples.html"

[[redirects]]
from = "/docs/cli.html"
to = "/docs/cli/installation.html"
